{{- range .Values.versions }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    {{- include "web.labels" $ | indent 4 }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "web.labels" $ | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "web.labels" $ | indent 8 }}
    spec:
      containers:
      - name: {{ .name }}
        image: "{{ $.Values.image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }} 
        ports:
        - containerPort: {{ $.Values.service.internalPort }}
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /StoreWebApp/config
      volumes:
      - name: config-volume
        configMap:
          name: {{ $.Release.Name }}-{{ $.Chart.Name }}-config
          items:
          - key: checks
            path: checks
          - key: default.json
            path: default.json
{{ end }}