{{ if .Values.ingress.enabled }} 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.bluemix.net/rewrite-path: "serviceName={{ .Release.Name }}-{{ .Chart.Name }} rewrite=/"
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    {{- include "web.labels" . | indent 4 }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
          servicePort: 80
{{- if .Values.ingress.hostname }}
    host: {{ .Values.ingress.hostname | quote }}
{{- end -}}
{{ end }}
