{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-vs
spec:
  hosts:
  - "*"
  gateways:
  - bluecompute-web-gateway
  http:
  # - match:
  #   - headers:
  #       user-agent:
  #         regex: '.*Firefox.*'
  #   route:
  #   - destination:
  #       host: {{ .Release.Name }}-web-canary.default.svc.cluster.local
  - route:
    - destination:
        host: {{ .Release.Name }}-web.default.svc.cluster.local
      weight: 50
    - destination:
        host: {{ .Release.Name }}-web-canary.default.svc.cluster.local
      weight: 50

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: web-destination
spec:
  host: {{ .Release.Name }}-web.default.svc.cluster.local
  subsets:
  - name: latest
    labels:
      version: latest

---

{{ if .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bluecompute-web-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: false
    hosts:
    - "*"
{{ end }} # istio gateway enablement

{{ end }} # istio enablement