{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-vs
spec:
  hosts:
  - "*"
  gateways:
  - bluecompute-web-gateway
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}-web.default.svc.cluster.local
        port:
          number: 80

---

{{ if .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bluecompute-web-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: false
    hosts:
    - "*"
{{ end }}

{{ end }}

---
