apiVersion: v1
entries:
  web:
  - apiVersion: v1
    created: "2019-08-13T10:44:22.031797-05:00"
    description: BlueCompute Web BFF app
    digest: 32962aaec0632529896fcd2a8321e49b1ef48d6bc84127e9d08082297c643a2b
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: web
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-bluecompute-web/tree/microprofile
    urls:
    - web-0.0.1.tgz
    version: 0.0.1
generated: "2019-08-13T10:44:22.029424-05:00"
